### PR TITLE
Trivia

### PR DESCRIPTION
**Pull request by DarianAmin**

### CODE REVIEW

**Review by LukeG294 — APPROVED** [review]
Looks good. Let's just make sure to keep adding questions/answers so we don't get repeats.

**Comment by DarianAmin** [comment]
I will look for some more.

**Comment by DarianAmin** [comment]
I have updated this code to fix the issues.

**Comment by LukeG294** [comment]
@bsoyka Is there anything missing or incorrect here? Or are you just holding off on merging? :)

**Comment by DarianAmin** [comment]
@bsoyka If there is I am happy to fix them.

**Comment by DarianAmin** [comment]
image

**Comment by DarianAmin** [comment]
This is an example of how it would work

**Review by LukeG294 — APPROVED** [review]

**Comment by DarianAmin** [comment]
I have just fixed some bugs with the code

**Comment by LukeG294** [comment]
@DarianAmin Wouldn't you just be able to put any of the answers and it would be considered correct?

**Comment by DarianAmin** [comment]
Yes you would. I think I have found a possible solution to it though 🤔

**Pull request closed without merging**
