### PR TITLE
NATO Phonetic Alphabet

### PR DESCRIPTION
**Pull request by DarianAmin**
#46

### CODE REVIEW

**Review by LukeG294 — APPROVED** [review]
Looks good to me.

**Comment by bsoyka** [comment]
@DarianAmin Mind if I make a few little refactoring/formatting changes?

**Comment by DarianAmin** [comment]
Sure

**Review by bsoyka — APPROVED** [review]
Sorry if I changed too much, but thanks for your contribution!

**Comment by LukeG294** [comment]
🎉

**Comment by DarianAmin** [comment]
Thanks

**Comment by bsoyka** [comment]
@all-contributors please add DarianAmin for ideas, code

**Pull request merged**
