### PR TITLE
!repeat Fix

### LINKED ISSUE #76: !repeat allows command injection
**Describe the bug**

Inputting another command inside `!repeat` arguments will lead to that command execution, allowing users to make the bot run certain commands by itself.

**To Reproduce**

Inserting any command inside `!repeat`. Example: `!repeat !command`

**Expected behavior**

The bot should just run `!repeat`, ignoring the injected command.

**Screenshots**

botissue

**Additional context**

It seems there is no verification whatsoever that prevents the bot from reading itself when listening for new commands.

### PR DESCRIPTION
**Pull request by LukeG294**
Closes #76 

## Summary

If a different command is added within the !repeat command, the repeat command will not run.

## Checklist
- [x] I have read and agree to follow the contributing guidelines and code of conduct in `CONTRIBUTING.md`.
- [x] An issue was made and assigned to me by a maintainer before opening this pull request.
- [x] I have formatted the code as detailed in `CONTRIBUTING.md`.
- [x] I have tested all the code in my pull request, including by running BrainBot as a whole.

### CODE REVIEW

**Review by bsoyka — CHANGES_REQUESTED** [review]
I think we should explore other ways of accomplishing this. For example, if I were to run `!repeat !shutdown abc`, it would still shut down the bot. How about replacing all `!`s with `\!`?

**Comment by LukeG294** [comment]
What do you mean by replacing all !s with \!? In just the repeat command?

**Comment by bsoyka** [comment]
Yep.

**Comment by LukeG294** [comment]
Just to be sure:

If someone said:

```
!repeat /shutdown 
```

It *should* shut down the bot.

But if I were to run:

```
!repeat !shutdown
```

It wouldn't?

**Comment by bsoyka** [comment]
No no no, let me explain this a bit better.

User runs:

`!repeat !shutdown`

Bot says:

`\!shutdown` (which shows up in Markdown as \!shutdown but isn't recognized as a command)

Basically, replace `!` with `\!` in the repeated text.

**Comment by LukeG294** [comment]
Makes sense, thanks for the clarification.

**Pull request closed without merging**
